services:
  api:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
  
volumes:
  pgdata:
